version: "3"
services:
  frontend:
    container_name: frontend-react-app
    build:
      context: .
    ports:
      - "3000:3000"
    #networks:
    #-
    volumes:
      - .:/app
  #  depends_on:
  #    - mysql
